# Copyright 2018, The max Contributors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
        - stage: build
          script: cd Projects/Clang\ X86\ Make && make
        - stage: test
          script: Projects/Clang\ X86\ Make/maxAutomatedTests
    - os: linux
      compiler: clang
        - stage: build
          script: cd Projects/Clang\ X86-64\ Make && make
        - stage: test
          script: Projects/Clang\ X86-64\ Make/maxAutomatedTests
    - os: linux
      compiler: gcc
        - stage: build
          script: cd Projects/GCC\ X86\ Make && make
        - stage: test
          script: Projects/GCC\ X86\ Make/maxAutomatedTests
    - os: linux
      compiler: gcc
        - stage: build
          script: cd Projects/GCC\ X86-64\ Make && make
        - stage: test
          script: Projects/GCC\ X86064\ Make/maxAutomatedTests
    #- os: osx
    #compiler: clang
